# Generated by Django 5.2.4 on 2025-10-05 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(choices=[('LIGHT', 'Lightweight'), ('MIDDLE', 'Middleweight'), ('CRUISER', 'Cruiserweight'), ('HEAVY', 'Heavyweight')])),
                ('weight_limit', models.IntegerField(validators=[django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('weight', models.IntegerField()),
                ('code', models.CharField(unique=True)),
                ('image', models.ImageField(upload_to='medications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='drone.drone')),
            ],
        ),
    ]
