# Generated by Django 5.2.4 on 2025-10-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0002_alter_drone_model_alter_drone_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
