# Generated by Django 5.2.7 on 2025-10-05 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0003_alter_drone_id_alter_medication_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='weight_limit',
            new_name='weight',
        ),
    ]
