# Generated by Django 5.2.7 on 2025-10-05 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0004_rename_weight_limit_drone_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='weight',
            new_name='weight_limit',
        ),
    ]
