# Generated by Django 5.2.4 on 2025-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone', '0005_rename_weight_drone_weight_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medications/'),
        ),
    ]
